{
 "title": "SQL exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   { "name": "relname", "label": "Table", "query": { "query": "label_values(relname)" } }
  ]
 },
 "panels": [
  {
   "title": "Table Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_db_stat_user_tables_size_bytes{target=~\"$datname\", relname=~\"$relname\"}",
     "legendFormat": "{{target}}.{{relname}}"
    }
   ]
  },
  { "title": "BufferCache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "BufferCache Total Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_db_buffercache_total_buffers{target=~\"$datname\", relname=~\"$relname\"}",
     "legendFormat": "{{target}}.{{relname}}"
    }
   ]
  },
  {
   "title": "BufferCache Dirty Buffers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pg_db_buffercache_dirty_buffers{target=~\"$datname\", relname=~\"$relname\"}",
     "legendFormat": "{{target}}.{{relname}}"
    }
   ]
  },
  {
   "title": "BufferCache Median Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "pg_db_buffercache_usage_median{target=~\"$datname\", relname=~\"$relname\"}",
     "legendFormat": "{{target}}.{{relname}}"
    }
   ]
  },
  {
   "title": "BufferCache Mean Usage Ratio",
   "type": "timeseries",
   "description": "Score is 1-5 per buffer. This returns the average score across all buffers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "pg_db_buffercache_usage_ratio{target=~\"$datname\", relname=~\"$relname\"}",
     "legendFormat": "{{target}}.{{relname}}"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "AutoVacuum/Analyze per table",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "rate(pg_db_stat_user_tables_autovacuum_count{target=~\"$datname\", relname=~\"$relname\"}[$__rate_interval])",
     "legendFormat": "AutoVacuum {{target}}.{{relname}}"
    },
    {
     "expr": "rate(pg_db_stat_user_tables_autoanalyze_count{target=~\"$datname\", relname=~\"$relname\"}[$__rate_interval])",
     "legendFormat": "AutoAnalyze {{target}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Dead Tuple By Table",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "pg_db_stat_user_tables_n_dead_tup{target=~\"$datname\", relname=~\"$relname\"}",
     "legendFormat": "{{target}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Hot Updates Per Table",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "rate(pg_db_stat_user_tables_n_tup_hot_upd{target=~\"$datname\", relname=~\"$relname\"}[$__rate_interval])",
     "legendFormat": "{{target}}.{{relname}}"
    }
   ]
  },
  { "title": "Statio per Table/Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Statio Index Blocks Hit",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "rate(pg_db_statio_user_indexes_idx_blks_hit{target=~\"$datname\", relname=~\"$relname\"}[$__rate_interval])",
     "legendFormat": "{{target}}.{{indexrelname}}"
    }
   ]
  },
  {
   "title": "Statio Index Blocks Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "rate(pg_db_statio_user_indexes_idx_blks_read{target=~\"$datname\", relname=~\"$relname\"}[$__rate_interval])",
     "legendFormat": "{{target}}.{{indexrelname}}"
    }
   ]
  },
  {
   "title": "Heap Blocks Hit per Table",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "rate(pg_db_statio_user_tables_heap_blks_hit{target=~\"$datname\", relname=~\"$relname\"}[$__rate_interval])",
     "legendFormat": "{{target}}.{{relname}}"
    }
   ]
  }
 ]
}